// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdDescription
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdDescription : IxtdLanguageRepresentation
	{
		xtdText @Description { get;  set; }
		IEnumerable<IxtdRoot> @is_description_of {  get; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdDescription", 23)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdDescription : xtdLanguageRepresentation, IInstantiableEntity, IxtdDescription, IContainsEntityReferences, IEquatable<@xtdDescription>
	{
		#region IxtdDescription explicit implementation
		xtdText IxtdDescription.Description { 
 
			get { return @Description; } 
			set { Description = value;}
		}	
		 
		IEnumerable<IxtdRoot> IxtdDescription.is_description_of {  get { return @is_description_of; } }
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdDescription(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdText _description;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(3, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 3)]
		public xtdText @Description 
		{ 
			get 
			{
				if(_activated) return _description;
				Activate();
				return _description;
			} 
			set
			{
				SetValue( v =>  _description = v, _description, value,  "Description", 3);
			} 
		}	
		#endregion



		#region Inverse attributes
		[InverseProperty("Descriptions")]
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 4)]
		public IEnumerable<xtdRoot> @is_description_of 
		{ 
			get 
			{
				return Model.Instances.Where<xtdRoot>(e => e.Descriptions != null &&  e.Descriptions.Contains(this), "Descriptions", this);
			} 
		}
		#endregion

		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 2: 
					_description = value.StringVal;
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdDescription other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				if (@LanguageName != null)
					yield return @LanguageName;
			}
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}