// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using Xbim.Common.Metadata;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdDimensionalExponents
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdDimensionalExponents : IPersistEntity
	{
		double @LengthExponent { get;  set; }
		double @MassExponent { get;  set; }
		double @TimeExponent { get;  set; }
		double @ElectricCurrentExponent { get;  set; }
		double @ThermodynamicTemperatureExponent { get;  set; }
		double @AmountOfSubstanceExponent { get;  set; }
		double @LuminousIntensityExponent { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdDimensionalExponents", 16)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdDimensionalExponents : PersistEntity, IInstantiableEntity, IxtdDimensionalExponents, IEquatable<@xtdDimensionalExponents>
	{
		#region IxtdDimensionalExponents explicit implementation
		double IxtdDimensionalExponents.LengthExponent { 
 
			get { return @LengthExponent; } 
			set { LengthExponent = value;}
		}	
		double IxtdDimensionalExponents.MassExponent { 
 
			get { return @MassExponent; } 
			set { MassExponent = value;}
		}	
		double IxtdDimensionalExponents.TimeExponent { 
 
			get { return @TimeExponent; } 
			set { TimeExponent = value;}
		}	
		double IxtdDimensionalExponents.ElectricCurrentExponent { 
 
			get { return @ElectricCurrentExponent; } 
			set { ElectricCurrentExponent = value;}
		}	
		double IxtdDimensionalExponents.ThermodynamicTemperatureExponent { 
 
			get { return @ThermodynamicTemperatureExponent; } 
			set { ThermodynamicTemperatureExponent = value;}
		}	
		double IxtdDimensionalExponents.AmountOfSubstanceExponent { 
 
			get { return @AmountOfSubstanceExponent; } 
			set { AmountOfSubstanceExponent = value;}
		}	
		double IxtdDimensionalExponents.LuminousIntensityExponent { 
 
			get { return @LuminousIntensityExponent; } 
			set { LuminousIntensityExponent = value;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdDimensionalExponents(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private double _lengthExponent;
		private double _massExponent;
		private double _timeExponent;
		private double _electricCurrentExponent;
		private double _thermodynamicTemperatureExponent;
		private double _amountOfSubstanceExponent;
		private double _luminousIntensityExponent;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(1, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 1)]
		public double @LengthExponent 
		{ 
			get 
			{
				if(_activated) return _lengthExponent;
				Activate();
				return _lengthExponent;
			} 
			set
			{
				SetValue( v =>  _lengthExponent = v, _lengthExponent, value,  "LengthExponent", 1);
			} 
		}	
		[EntityAttribute(2, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 2)]
		public double @MassExponent 
		{ 
			get 
			{
				if(_activated) return _massExponent;
				Activate();
				return _massExponent;
			} 
			set
			{
				SetValue( v =>  _massExponent = v, _massExponent, value,  "MassExponent", 2);
			} 
		}	
		[EntityAttribute(3, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 3)]
		public double @TimeExponent 
		{ 
			get 
			{
				if(_activated) return _timeExponent;
				Activate();
				return _timeExponent;
			} 
			set
			{
				SetValue( v =>  _timeExponent = v, _timeExponent, value,  "TimeExponent", 3);
			} 
		}	
		[EntityAttribute(4, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 4)]
		public double @ElectricCurrentExponent 
		{ 
			get 
			{
				if(_activated) return _electricCurrentExponent;
				Activate();
				return _electricCurrentExponent;
			} 
			set
			{
				SetValue( v =>  _electricCurrentExponent = v, _electricCurrentExponent, value,  "ElectricCurrentExponent", 4);
			} 
		}	
		[EntityAttribute(5, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 5)]
		public double @ThermodynamicTemperatureExponent 
		{ 
			get 
			{
				if(_activated) return _thermodynamicTemperatureExponent;
				Activate();
				return _thermodynamicTemperatureExponent;
			} 
			set
			{
				SetValue( v =>  _thermodynamicTemperatureExponent = v, _thermodynamicTemperatureExponent, value,  "ThermodynamicTemperatureExponent", 5);
			} 
		}	
		[EntityAttribute(6, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 6)]
		public double @AmountOfSubstanceExponent 
		{ 
			get 
			{
				if(_activated) return _amountOfSubstanceExponent;
				Activate();
				return _amountOfSubstanceExponent;
			} 
			set
			{
				SetValue( v =>  _amountOfSubstanceExponent = v, _amountOfSubstanceExponent, value,  "AmountOfSubstanceExponent", 6);
			} 
		}	
		[EntityAttribute(7, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 7)]
		public double @LuminousIntensityExponent 
		{ 
			get 
			{
				if(_activated) return _luminousIntensityExponent;
				Activate();
				return _luminousIntensityExponent;
			} 
			set
			{
				SetValue( v =>  _luminousIntensityExponent = v, _luminousIntensityExponent, value,  "LuminousIntensityExponent", 7);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
					_lengthExponent = value.RealVal;
					return;
				case 1: 
					_massExponent = value.RealVal;
					return;
				case 2: 
					_timeExponent = value.RealVal;
					return;
				case 3: 
					_electricCurrentExponent = value.RealVal;
					return;
				case 4: 
					_thermodynamicTemperatureExponent = value.RealVal;
					return;
				case 5: 
					_amountOfSubstanceExponent = value.RealVal;
					return;
				case 6: 
					_luminousIntensityExponent = value.RealVal;
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdDimensionalExponents other)
	    {
	        return this == other;
	    }
        #endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
        public override string ToString()
        {
            return $"[{LengthExponent:N2} {MassExponent:N2} {TimeExponent:N2} {ElectricCurrentExponent:N2} {ThermodynamicTemperatureExponent:N2} {AmountOfSubstanceExponent:N2} {LuminousIntensityExponent:N2}]";
        }

        public xtdDimensionalExponents Clone(IModel model)
        {
            return model.Instances.New<xtdDimensionalExponents>(d => {
                d.LengthExponent = LengthExponent;
                d.MassExponent = MassExponent;
                d.TimeExponent = TimeExponent;
                d.ElectricCurrentExponent = ElectricCurrentExponent;
                d.ThermodynamicTemperatureExponent = ThermodynamicTemperatureExponent;
                d.AmountOfSubstanceExponent = AmountOfSubstanceExponent;
                d.LuminousIntensityExponent = LuminousIntensityExponent;
            });
        }

        public xtdDimensionalExponents(
            double lengthExponent, 
            double massExponent, 
            double timeExponent, 
            double electricCurrentExponent, 
            double thermodynamicTemperatureExponent, 
            double amountOfSubstanceExponent, 
            double luminousIntensityExponent) 
                : base (null, -1, true)
        {
            _lengthExponent = lengthExponent;
            _massExponent = massExponent;
            _timeExponent = timeExponent;
            _electricCurrentExponent = electricCurrentExponent;
            _thermodynamicTemperatureExponent = thermodynamicTemperatureExponent;
            _amountOfSubstanceExponent = amountOfSubstanceExponent;
            _luminousIntensityExponent = luminousIntensityExponent;
        }
        //##
		#endregion
	}
}