// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdLogicalConstraint
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdLogicalConstraint : IxtdConstraint
	{
		xtdLogicalOperatorEnum @LogicalOperator { get;  set; }
		IItemSet<IxtdConstraint> @Constraints { get; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdLogicalConstraint", 4)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdLogicalConstraint : xtdConstraint, IInstantiableEntity, IxtdLogicalConstraint, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdLogicalConstraint>
	{
		#region IxtdLogicalConstraint explicit implementation
		xtdLogicalOperatorEnum IxtdLogicalConstraint.LogicalOperator { 
 
			get { return @LogicalOperator; } 
			set { LogicalOperator = value;}
		}	
		IItemSet<IxtdConstraint> IxtdLogicalConstraint.Constraints { 
			get { return new Common.Collections.ProxyItemSet<xtdConstraint, IxtdConstraint>( @Constraints); } 
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdLogicalConstraint(IModel model, int label, bool activated) : base(model, label, activated)  
		{
			_constraints = new ItemSet<xtdConstraint>( this, 0,  7);
		}

		#region Explicit attribute fields
		private xtdLogicalOperatorEnum _logicalOperator;
		private readonly ItemSet<xtdConstraint> _constraints;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(6, EntityAttributeState.Mandatory, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 6)]
		public xtdLogicalOperatorEnum @LogicalOperator 
		{ 
			get 
			{
				if(_activated) return _logicalOperator;
				Activate();
				return _logicalOperator;
			} 
			set
			{
				SetValue( v =>  _logicalOperator = v, _logicalOperator, value,  "LogicalOperator", 6);
			} 
		}	
		[EntityAttribute(7, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 7)]
		public IItemSet<xtdConstraint> @Constraints 
		{ 
			get 
			{
				if(_activated) return _constraints;
				Activate();
				return _constraints;
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 5: 
                    _logicalOperator = (xtdLogicalOperatorEnum) System.Enum.Parse(typeof (xtdLogicalOperatorEnum), value.EnumVal, true);
					return;
				case 6: 
					_constraints.InternalAdd((xtdConstraint)value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdLogicalConstraint other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				foreach(var entity in @Constraints)
					yield return entity;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}