// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdMeasureIntervalConstraint
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdMeasureIntervalConstraint : IxtdConstraint
	{
		xtdReal @UpperBoundary { get;  set; }
		xtdReal @LowerBoundary { get;  set; }
		bool @IncludingUpperBoundary { get;  set; }
		bool @IncludingLowerBoundary { get;  set; }
		IxtdUnit @ValuesUnit { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdMeasureIntervalConstraint", 2)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdMeasureIntervalConstraint : xtdConstraint, IInstantiableEntity, IxtdMeasureIntervalConstraint, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdMeasureIntervalConstraint>
	{
		#region IxtdMeasureIntervalConstraint explicit implementation
		xtdReal IxtdMeasureIntervalConstraint.UpperBoundary { 
 
			get { return @UpperBoundary; } 
			set { UpperBoundary = value;}
		}	
		xtdReal IxtdMeasureIntervalConstraint.LowerBoundary { 
 
			get { return @LowerBoundary; } 
			set { LowerBoundary = value;}
		}	
		bool IxtdMeasureIntervalConstraint.IncludingUpperBoundary { 
 
			get { return @IncludingUpperBoundary; } 
			set { IncludingUpperBoundary = value;}
		}	
		bool IxtdMeasureIntervalConstraint.IncludingLowerBoundary { 
 
			get { return @IncludingLowerBoundary; } 
			set { IncludingLowerBoundary = value;}
		}	
		IxtdUnit IxtdMeasureIntervalConstraint.ValuesUnit { 
 
 
			get { return @ValuesUnit; } 
			set { ValuesUnit = value as xtdUnit;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdMeasureIntervalConstraint(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdReal _upperBoundary;
		private xtdReal _lowerBoundary;
		private bool _includingUpperBoundary;
		private bool _includingLowerBoundary;
		private xtdUnit _valuesUnit;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(6, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 6)]
		public xtdReal @UpperBoundary 
		{ 
			get 
			{
				if(_activated) return _upperBoundary;
				Activate();
				return _upperBoundary;
			} 
			set
			{
				SetValue( v =>  _upperBoundary = v, _upperBoundary, value,  "UpperBoundary", 6);
			} 
		}	
		[EntityAttribute(7, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 7)]
		public xtdReal @LowerBoundary 
		{ 
			get 
			{
				if(_activated) return _lowerBoundary;
				Activate();
				return _lowerBoundary;
			} 
			set
			{
				SetValue( v =>  _lowerBoundary = v, _lowerBoundary, value,  "LowerBoundary", 7);
			} 
		}	
		[EntityAttribute(8, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 8)]
		public bool @IncludingUpperBoundary 
		{ 
			get 
			{
				if(_activated) return _includingUpperBoundary;
				Activate();
				return _includingUpperBoundary;
			} 
			set
			{
				SetValue( v =>  _includingUpperBoundary = v, _includingUpperBoundary, value,  "IncludingUpperBoundary", 8);
			} 
		}	
		[EntityAttribute(9, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 9)]
		public bool @IncludingLowerBoundary 
		{ 
			get 
			{
				if(_activated) return _includingLowerBoundary;
				Activate();
				return _includingLowerBoundary;
			} 
			set
			{
				SetValue( v =>  _includingLowerBoundary = v, _includingLowerBoundary, value,  "IncludingLowerBoundary", 9);
			} 
		}	
		[EntityAttribute(10, EntityAttributeState.Optional, EntityAttributeType.Class, EntityAttributeType.None, null, null, 10)]
		public xtdUnit @ValuesUnit 
		{ 
			get 
			{
				if(_activated) return _valuesUnit;
				Activate();
				return _valuesUnit;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _valuesUnit = v, _valuesUnit, value,  "ValuesUnit", 10);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 5: 
					_upperBoundary = value.RealVal;
					return;
				case 6: 
					_lowerBoundary = value.RealVal;
					return;
				case 7: 
					_includingUpperBoundary = value.BooleanVal;
					return;
				case 8: 
					_includingLowerBoundary = value.BooleanVal;
					return;
				case 9: 
					_valuesUnit = (xtdUnit)(value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdMeasureIntervalConstraint other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				if (@ValuesUnit != null)
					yield return @ValuesUnit;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}