// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdMeasureWithUnit
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdMeasureWithUnit : IxtdObject
	{
		IxtdUnit @UnitComponent { get;  set; }
		IItemSet<IxtdValue> @ValueDomain { get; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdMeasureWithUnit", 46)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdMeasureWithUnit : xtdObject, IInstantiableEntity, IxtdMeasureWithUnit, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdMeasureWithUnit>
	{
		#region IxtdMeasureWithUnit explicit implementation
		IxtdUnit IxtdMeasureWithUnit.UnitComponent { 
 
 
			get { return @UnitComponent; } 
			set { UnitComponent = value as xtdUnit;}
		}	
		IItemSet<IxtdValue> IxtdMeasureWithUnit.ValueDomain { 
			get { return new Common.Collections.ProxyItemSet<xtdValue, IxtdValue>( @ValueDomain); } 
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdMeasureWithUnit(IModel model, int label, bool activated) : base(model, label, activated)  
		{
			_valueDomain = new OptionalItemSet<xtdValue>( this, 0,  7);
		}

		#region Explicit attribute fields
		private xtdUnit _unitComponent;
		private readonly OptionalItemSet<xtdValue> _valueDomain;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(6, EntityAttributeState.Optional, EntityAttributeType.Class, EntityAttributeType.None, null, null, 6)]
		public xtdUnit @UnitComponent 
		{ 
			get 
			{
				if(_activated) return _unitComponent;
				Activate();
				return _unitComponent;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _unitComponent = v, _unitComponent, value,  "UnitComponent", 6);
			} 
		}	
		[EntityAttribute(7, EntityAttributeState.Optional, EntityAttributeType.List, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 7)]
		public IOptionalItemSet<xtdValue> @ValueDomain 
		{ 
			get 
			{
				if(_activated) return _valueDomain;
				Activate();
				return _valueDomain;
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 5: 
					_unitComponent = (xtdUnit)(value.EntityVal);
					return;
				case 6: 
					_valueDomain.InternalAdd((xtdValue)value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdMeasureWithUnit other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				if (@UnitComponent != null)
					yield return @UnitComponent;
				foreach(var entity in @ValueDomain)
					yield return entity;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}