// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using Xbim.Common.Metadata;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdNamedUnit
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdNamedUnit : IPersistEntity, xtdUnitDefinition
	{
		IxtdDimensionalExponents @Dimensions { get;  set; }
		xtdUnitEnum @UnitType { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdNamedUnit", 18)]
	// ReSharper disable once PartialTypeWithSinglePart
	public abstract partial class @xtdNamedUnit : PersistEntity, IxtdNamedUnit, IEquatable<@xtdNamedUnit>
	{
		#region IxtdNamedUnit explicit implementation
		IxtdDimensionalExponents IxtdNamedUnit.Dimensions { 
 
 
			get { return @Dimensions; } 
			set { Dimensions = value as xtdDimensionalExponents;}
		}	
		xtdUnitEnum IxtdNamedUnit.UnitType { 
 
			get { return @UnitType; } 
			set { UnitType = value;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdNamedUnit(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdDimensionalExponents _dimensions;
		private xtdUnitEnum _unitType;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(1, EntityAttributeState.Mandatory, EntityAttributeType.Class, EntityAttributeType.None, null, null, 1)]
		public virtual xtdDimensionalExponents @Dimensions 
		{ 
			get 
			{
				if(_activated) return _dimensions;
				Activate();
				return _dimensions;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _dimensions = v, _dimensions, value,  "Dimensions", 1);
			} 
		}	
		[EntityAttribute(2, EntityAttributeState.Mandatory, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 2)]
		public xtdUnitEnum @UnitType 
		{ 
			get 
			{
				if(_activated) return _unitType;
				Activate();
				return _unitType;
			} 
			set
			{
				SetValue( v =>  _unitType = v, _unitType, value,  "UnitType", 2);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
					_dimensions = (xtdDimensionalExponents)(value.EntityVal);
					return;
				case 1: 
                    _unitType = (xtdUnitEnum) System.Enum.Parse(typeof (xtdUnitEnum), value.EnumVal, true);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdNamedUnit other)
	    {
	        return this == other;
	    }
        #endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}