// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdRelDocuments
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdRelDocuments : IxtdRelationship
	{
		IItemSet<IxtdObject> @RelatedObjects { get; }
		IxtdExternalDocument @RelatingDocument { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdRelDocuments", 62)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdRelDocuments : xtdRelationship, IInstantiableEntity, IxtdRelDocuments, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdRelDocuments>
	{
		#region IxtdRelDocuments explicit implementation
		IItemSet<IxtdObject> IxtdRelDocuments.RelatedObjects { 
			get { return new Common.Collections.ProxyItemSet<xtdObject, IxtdObject>( @RelatedObjects); } 
		}	
		IxtdExternalDocument IxtdRelDocuments.RelatingDocument { 
 
 
			get { return @RelatingDocument; } 
			set { RelatingDocument = value as xtdExternalDocument;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdRelDocuments(IModel model, int label, bool activated) : base(model, label, activated)  
		{
			_relatedObjects = new ItemSet<xtdObject>( this, 0,  7);
		}

		#region Explicit attribute fields
		private readonly ItemSet<xtdObject> _relatedObjects;
		private xtdExternalDocument _relatingDocument;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(7, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 7)]
		public IItemSet<xtdObject> @RelatedObjects 
		{ 
			get 
			{
				if(_activated) return _relatedObjects;
				Activate();
				return _relatedObjects;
			} 
		}	
		[EntityAttribute(8, EntityAttributeState.Mandatory, EntityAttributeType.Class, EntityAttributeType.None, null, null, 8)]
		public xtdExternalDocument @RelatingDocument 
		{ 
			get 
			{
				if(_activated) return _relatingDocument;
				Activate();
				return _relatingDocument;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _relatingDocument = v, _relatingDocument, value,  "RelatingDocument", 8);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
				case 5: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 6: 
					_relatedObjects.InternalAdd((xtdObject)value.EntityVal);
					return;
				case 7: 
					_relatingDocument = (xtdExternalDocument)(value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdRelDocuments other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				if (@ViewSelector != null)
					yield return @ViewSelector;
				foreach(var entity in @RelatedObjects)
					yield return entity;
				if (@RelatingDocument != null)
					yield return @RelatingDocument;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}