// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V4.Interfaces;
using Xbim.ISO_12006_3_V4;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdSIUnit
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdSIUnit : IxtdNamedUnit
	{
		xtdSIPrefix? @Prefix { get;  set; }
		xtdSIUnitName @Name { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V4
{
	[ExpressType("xtdSIUnit", 15)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdSIUnit : xtdNamedUnit, IInstantiableEntity, IxtdSIUnit, IEquatable<@xtdSIUnit>
	{
		#region IxtdSIUnit explicit implementation
		xtdSIPrefix? IxtdSIUnit.Prefix { 
 
			get { return @Prefix; } 
			set { Prefix = value;}
		}	
		xtdSIUnitName IxtdSIUnit.Name { 
 
			get { return @Name; } 
			set { Name = value;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdSIUnit(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdSIPrefix? _prefix;
		private xtdSIUnitName _name;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(3, EntityAttributeState.Optional, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 3)]
		public xtdSIPrefix? @Prefix 
		{ 
			get 
			{
				if(_activated) return _prefix;
				Activate();
				return _prefix;
			} 
			set
			{
				SetValue( v =>  _prefix = v, _prefix, value,  "Prefix", 3);
			} 
		}	
		[EntityAttribute(4, EntityAttributeState.Mandatory, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 4)]
		public xtdSIUnitName @Name 
		{ 
			get 
			{
				if(_activated) return _name;
				Activate();
				return _name;
			} 
			set
			{
				SetValue( v =>  _name = v, _name, value,  "Name", 4);
			} 
		}	
		#endregion

		#region Overriding attributes
		[EntityAttribute(1, EntityAttributeState.DerivedOverride, EntityAttributeType.Class, EntityAttributeType.None, null, null, 0)]
		public override xtdDimensionalExponents @Dimensions 
		{
			get 
			{
				return xtdDimensionsForSiUnit(Name);
			}
			set 
			{ 
				throw new System.Exception("It is not possible to set a value of derived property Dimensions in xtdSIUnit"); 
			}
		}
		#endregion



		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 2: 
                    _prefix = (xtdSIPrefix) System.Enum.Parse(typeof (xtdSIPrefix), value.EnumVal, true);
					return;
				case 3: 
                    _name = (xtdSIUnitName) System.Enum.Parse(typeof (xtdSIUnitName), value.EnumVal, true);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdSIUnit other)
	    {
	        return this == other;
	    }
        #endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}