// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Common;
using Xbim.ISO_12006_3_V4.Interfaces;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V4
{
    // ReSharper disable once InconsistentNaming
    // ReSharper disable once PartialTypeWithSinglePart
	public partial interface xtdValueType : IxtdValueType
	{
		#region Custom code for a select
		//## Custom code for a select
		//##
		#endregion
	}
}

namespace Xbim.ISO_12006_3_V4.Interfaces
{
	public partial interface IxtdValueType : IExpressSelectType, IExpressValueType
	{
		#region Custom code for a select interface
		//## Custom code for a select interface
		//##
		#endregion
	}
}