// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using Xbim.Common.Metadata;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V3.Interfaces;
using Xbim.ISO_12006_3_V3;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V3.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdExternalDocument
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdExternalDocument : IPersistEntity
	{
		xtdGlobalUniqueID @UniqueID { get;  set; }
		IItemSet<IxtdName> @Names { get; }
	
	}
}

namespace Xbim.ISO_12006_3_V3
{
	[ExpressType("xtdExternalDocument", 14)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdExternalDocument : PersistEntity, IInstantiableEntity, IxtdExternalDocument, IContainsEntityReferences, IEquatable<@xtdExternalDocument>
	{
		#region IxtdExternalDocument explicit implementation
		xtdGlobalUniqueID IxtdExternalDocument.UniqueID { 
 
			get { return @UniqueID; } 
			set { UniqueID = value;}
		}	
		IItemSet<IxtdName> IxtdExternalDocument.Names { 
			get { return new Common.Collections.ProxyItemSet<xtdName, IxtdName>( @Names); } 
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdExternalDocument(IModel model, int label, bool activated) : base(model, label, activated)  
		{
			_names = new ItemSet<xtdName>( this, 0,  2);
		}

		#region Explicit attribute fields
		private xtdGlobalUniqueID _uniqueID;
		private readonly ItemSet<xtdName> _names;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(1, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 1)]
		public xtdGlobalUniqueID @UniqueID 
		{ 
			get 
			{
				if(_activated) return _uniqueID;
				Activate();
				return _uniqueID;
			} 
			set
			{
				SetValue( v =>  _uniqueID = v, _uniqueID, value,  "UniqueID", 1);
			} 
		}	
		[EntityAttribute(2, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 2)]
		public IItemSet<xtdName> @Names 
		{ 
			get 
			{
				if(_activated) return _names;
				Activate();
				return _names;
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
					_uniqueID = value.StringVal;
					return;
				case 1: 
					_names.InternalAdd((xtdName)value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdExternalDocument other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Names)
					yield return entity;
			}
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}