// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V3.Interfaces;
using Xbim.ISO_12006_3_V3;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V3.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdName
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdName : IxtdLanguageRepresentation
	{
		xtdLabel @Name { get;  set; }
		IEnumerable<IxtdRoot> @is_name_of {  get; }
	
	}
}

namespace Xbim.ISO_12006_3_V3
{
	[ExpressType("xtdName", 18)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdName : xtdLanguageRepresentation, IInstantiableEntity, IxtdName, IContainsEntityReferences, IEquatable<@xtdName>
	{
		#region IxtdName explicit implementation
		xtdLabel IxtdName.Name { 
 
			get { return @Name; } 
			set { Name = value;}
		}	
		 
		IEnumerable<IxtdRoot> IxtdName.is_name_of {  get { return @is_name_of; } }
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdName(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdLabel _name;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(3, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 3)]
		public xtdLabel @Name 
		{ 
			get 
			{
				if(_activated) return _name;
				Activate();
				return _name;
			} 
			set
			{
				SetValue( v =>  _name = v, _name, value,  "Name", 3);
			} 
		}	
		#endregion



		#region Inverse attributes
		[InverseProperty("Names")]
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { -1 }, 4)]
		public IEnumerable<xtdRoot> @is_name_of 
		{ 
			get 
			{
				return Model.Instances.Where<xtdRoot>(e => e.Names != null &&  e.Names.Contains(this), "Names", this);
			} 
		}
		#endregion

		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 2: 
					_name = value.StringVal;
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdName other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				if (@LanguageName != null)
					yield return @LanguageName;
			}
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}