// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V3.Interfaces;
using Xbim.ISO_12006_3_V3;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V3.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdRelSequences
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdRelSequences : IxtdRelationship
	{
		IxtdActivity @RelatingActivity { get;  set; }
		IxtdActivity @RelatedActivity { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V3
{
	[ExpressType("xtdRelSequences", 35)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdRelSequences : xtdRelationship, IInstantiableEntity, IxtdRelSequences, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdRelSequences>
	{
		#region IxtdRelSequences explicit implementation
		IxtdActivity IxtdRelSequences.RelatingActivity { 
 
 
			get { return @RelatingActivity; } 
			set { RelatingActivity = value as xtdActivity;}
		}	
		IxtdActivity IxtdRelSequences.RelatedActivity { 
 
 
			get { return @RelatedActivity; } 
			set { RelatedActivity = value as xtdActivity;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdRelSequences(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdActivity _relatingActivity;
		private xtdActivity _relatedActivity;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(7, EntityAttributeState.Optional, EntityAttributeType.Class, EntityAttributeType.None, null, null, 7)]
		public xtdActivity @RelatingActivity 
		{ 
			get 
			{
				if(_activated) return _relatingActivity;
				Activate();
				return _relatingActivity;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _relatingActivity = v, _relatingActivity, value,  "RelatingActivity", 7);
			} 
		}	
		[EntityAttribute(8, EntityAttributeState.Optional, EntityAttributeType.Class, EntityAttributeType.None, null, null, 8)]
		public xtdActivity @RelatedActivity 
		{ 
			get 
			{
				if(_activated) return _relatedActivity;
				Activate();
				return _relatedActivity;
			} 
			set
			{
				if (value != null && !(ReferenceEquals(Model, value.Model)))
					throw new XbimException("Cross model entity assignment.");
				SetValue( v =>  _relatedActivity = v, _relatedActivity, value,  "RelatedActivity", 8);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
				case 5: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 6: 
					_relatingActivity = (xtdActivity)(value.EntityVal);
					return;
				case 7: 
					_relatedActivity = (xtdActivity)(value.EntityVal);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdRelSequences other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				if (@ViewSelector != null)
					yield return @ViewSelector;
				if (@RelatingActivity != null)
					yield return @RelatingActivity;
				if (@RelatedActivity != null)
					yield return @RelatedActivity;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}