// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.ISO_12006_3_V3
{
	public enum xtdToleranceTypeEnum : byte
	{
		@REALVALUE ,
		@PERCENTAGE 
	}
}