// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.ISO_12006_3_V3.Interfaces;
using Xbim.ISO_12006_3_V3;
//## Custom using statements
//##

namespace Xbim.ISO_12006_3_V3.Interfaces
{
	/// <summary>
    /// Readonly interface for xtdValue
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IxtdValue : IxtdObject
	{
		xtdText? @LowerTolerance { get;  set; }
		xtdText? @NominalValue { get;  set; }
		xtdText? @UpperTolerance { get;  set; }
		xtdValueTypeEnum? @ValueType { get;  set; }
		xtdValueRoleEnum? @ValueRole { get;  set; }
		xtdToleranceTypeEnum? @ToleranceType { get;  set; }
	
	}
}

namespace Xbim.ISO_12006_3_V3
{
	[ExpressType("xtdValue", 40)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @xtdValue : xtdObject, IInstantiableEntity, IxtdValue, IContainsEntityReferences, IContainsIndexedReferences, IEquatable<@xtdValue>
	{
		#region IxtdValue explicit implementation
		xtdText? IxtdValue.LowerTolerance { 
 
			get { return @LowerTolerance; } 
			set { LowerTolerance = value;}
		}	
		xtdText? IxtdValue.NominalValue { 
 
			get { return @NominalValue; } 
			set { NominalValue = value;}
		}	
		xtdText? IxtdValue.UpperTolerance { 
 
			get { return @UpperTolerance; } 
			set { UpperTolerance = value;}
		}	
		xtdValueTypeEnum? IxtdValue.ValueType { 
 
			get { return @ValueType; } 
			set { ValueType = value;}
		}	
		xtdValueRoleEnum? IxtdValue.ValueRole { 
 
			get { return @ValueRole; } 
			set { ValueRole = value;}
		}	
		xtdToleranceTypeEnum? IxtdValue.ToleranceType { 
 
			get { return @ToleranceType; } 
			set { ToleranceType = value;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal xtdValue(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private xtdText? _lowerTolerance;
		private xtdText? _nominalValue;
		private xtdText? _upperTolerance;
		private xtdValueTypeEnum? _valueType;
		private xtdValueRoleEnum? _valueRole;
		private xtdToleranceTypeEnum? _toleranceType;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(6, EntityAttributeState.Optional, EntityAttributeType.None, EntityAttributeType.None, null, null, 6)]
		public xtdText? @LowerTolerance 
		{ 
			get 
			{
				if(_activated) return _lowerTolerance;
				Activate();
				return _lowerTolerance;
			} 
			set
			{
				SetValue( v =>  _lowerTolerance = v, _lowerTolerance, value,  "LowerTolerance", 6);
			} 
		}	
		[EntityAttribute(7, EntityAttributeState.Optional, EntityAttributeType.None, EntityAttributeType.None, null, null, 7)]
		public xtdText? @NominalValue 
		{ 
			get 
			{
				if(_activated) return _nominalValue;
				Activate();
				return _nominalValue;
			} 
			set
			{
				SetValue( v =>  _nominalValue = v, _nominalValue, value,  "NominalValue", 7);
			} 
		}	
		[EntityAttribute(8, EntityAttributeState.Optional, EntityAttributeType.None, EntityAttributeType.None, null, null, 8)]
		public xtdText? @UpperTolerance 
		{ 
			get 
			{
				if(_activated) return _upperTolerance;
				Activate();
				return _upperTolerance;
			} 
			set
			{
				SetValue( v =>  _upperTolerance = v, _upperTolerance, value,  "UpperTolerance", 8);
			} 
		}	
		[EntityAttribute(9, EntityAttributeState.Optional, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 9)]
		public xtdValueTypeEnum? @ValueType 
		{ 
			get 
			{
				if(_activated) return _valueType;
				Activate();
				return _valueType;
			} 
			set
			{
				SetValue( v =>  _valueType = v, _valueType, value,  "ValueType", 9);
			} 
		}	
		[EntityAttribute(10, EntityAttributeState.Optional, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 10)]
		public xtdValueRoleEnum? @ValueRole 
		{ 
			get 
			{
				if(_activated) return _valueRole;
				Activate();
				return _valueRole;
			} 
			set
			{
				SetValue( v =>  _valueRole = v, _valueRole, value,  "ValueRole", 10);
			} 
		}	
		[EntityAttribute(11, EntityAttributeState.Optional, EntityAttributeType.Enum, EntityAttributeType.None, null, null, 11)]
		public xtdToleranceTypeEnum? @ToleranceType 
		{ 
			get 
			{
				if(_activated) return _toleranceType;
				Activate();
				return _toleranceType;
			} 
			set
			{
				SetValue( v =>  _toleranceType = v, _toleranceType, value,  "ToleranceType", 11);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
				case 1: 
				case 2: 
				case 3: 
				case 4: 
					base.Parse(propIndex, value, nestedIndex); 
					return;
				case 5: 
					_lowerTolerance = value.StringVal;
					return;
				case 6: 
					_nominalValue = value.StringVal;
					return;
				case 7: 
					_upperTolerance = value.StringVal;
					return;
				case 8: 
                    _valueType = (xtdValueTypeEnum) System.Enum.Parse(typeof (xtdValueTypeEnum), value.EnumVal, true);
					return;
				case 9: 
                    _valueRole = (xtdValueRoleEnum) System.Enum.Parse(typeof (xtdValueRoleEnum), value.EnumVal, true);
					return;
				case 10: 
                    _toleranceType = (xtdToleranceTypeEnum) System.Enum.Parse(typeof (xtdToleranceTypeEnum), value.EnumVal, true);
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@xtdValue other)
	    {
	        return this == other;
	    }
        #endregion

		#region IContainsEntityReferences
		IEnumerable<IPersistEntity> IContainsEntityReferences.References 
		{
			get 
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
			}
		}
		#endregion


		#region IContainsIndexedReferences
        IEnumerable<IPersistEntity> IContainsIndexedReferences.IndexedReferences 
		{ 
			get
			{
				foreach(var entity in @Descriptions)
					yield return entity;
				foreach(var entity in @Names)
					yield return entity;
				
			} 
		}
		#endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}